import type { BuiltinCommand } from "./types";

export const SELECTORS = [
  // Interactive
  "button",
  "a[href]",
  "input",
  "textarea",
  "select",
  "form",
  // Media
  "img[alt]",
  "video",
  "audio",
  // Structure
  "details",
  "summary",
  "dialog",
  "nav",
  "table",
  "label[for]",
  // Headings
  "h1", "h2", "h3", "h4", "h5", "h6",
  // ARIA roles
  '[role="button"]',
  '[role="tab"]',
  '[role="tabpanel"]',
  '[role="menuitem"]',
  '[role="menu"]',
  '[role="switch"]',
  '[role="checkbox"]',
  '[role="radio"]',
  '[role="link"]',
  '[role="slider"]',
  '[role="progressbar"]',
  '[role="alert"]',
  '[role="dialog"]',
  '[role="listbox"]',
  '[role="option"]',
  '[role="tree"]',
  '[role="treeitem"]',
  '[role="combobox"]',
  '[role="searchbox"]',
  '[role="navigation"]',
  '[role="banner"]',
  '[role="complementary"]',
  '[role="contentinfo"]',
  // Custom interactives
  "[onclick]",
  "[data-action]",
  "[data-toggle]",
  "[data-target]",
  "[data-bs-toggle]",
  "[tabindex]",
  "[contenteditable]",
  // Common framework patterns
  "[ng-click]",
];

export const BUILTIN_COMMANDS: BuiltinCommand[] = [
  {
    keyword: "dark mode",
    aliases: ["dark", "theme", "night mode", "invert", "light mode"],
    action: "dark-mode",
    icon: "🌙",
    label: "Toggle Dark Mode",
    description: "Invert page colors for dark viewing",
  },
  {
    keyword: "read mode",
    aliases: ["reader", "reading", "focus mode", "distraction free", "clean"],
    action: "read-mode",
    icon: "📖",
    label: "Toggle Reader Mode",
    description: "Strip navigation, focus on content",
  },
  {
    keyword: "hide images",
    aliases: ["no images", "text only", "hide media", "remove images"],
    action: "hide-images",
    icon: "🖼️",
    label: "Toggle Hide Images",
    description: "Fade out images and videos",
  },
  {
    keyword: "scroll top",
    aliases: ["go top", "top", "beginning", "start"],
    action: "scroll-top",
    icon: "⬆️",
    label: "Scroll to Top",
    description: "Jump to the top of the page",
  },
  {
    keyword: "scroll bottom",
    aliases: ["go bottom", "bottom", "end"],
    action: "scroll-bottom",
    icon: "⬇️",
    label: "Scroll to Bottom",
    description: "Jump to the bottom of the page",
  },
  {
    keyword: "zoom in",
    aliases: ["bigger", "enlarge", "magnify"],
    action: "zoom-in",
    icon: "🔍",
    label: "Zoom In",
    description: "Increase page zoom by 10%",
  },
  {
    keyword: "zoom out",
    aliases: ["smaller", "shrink"],
    action: "zoom-out",
    icon: "🔎",
    label: "Zoom Out",
    description: "Decrease page zoom by 10%",
  },
  {
    keyword: "zoom reset",
    aliases: ["normal zoom", "reset zoom", "100%"],
    action: "zoom-reset",
    icon: "🔄",
    label: "Reset Zoom",
    description: "Reset zoom to 100%",
  },
  {
    keyword: "print",
    aliases: ["print page", "save pdf"],
    action: "print",
    icon: "🖨️",
    label: "Print Page",
    description: "Open print dialog",
  },
  {
    keyword: "copy url",
    aliases: ["copy link", "share", "copy address"],
    action: "copy-url",
    icon: "📋",
    label: "Copy Page URL",
    description: "Copy current page URL to clipboard",
  },
  {
    keyword: "fullscreen",
    aliases: ["full screen", "maximize"],
    action: "fullscreen",
    icon: "⛶",
    label: "Toggle Fullscreen",
    description: "Enter or exit fullscreen mode",
  },
  {
    keyword: "highlight links",
    aliases: ["show links", "find links", "all links"],
    action: "highlight-links",
    icon: "🔗",
    label: "Highlight All Links",
    description: "Outline every link on the page",
  },
  {
    keyword: "page info",
    aliases: ["page stats", "statistics", "meta"],
    action: "page-info",
    icon: "📊",
    label: "Show Page Info",
    description: "Count elements, links, images on page",
  },
  {
    keyword: "disable css",
    aliases: ["no css", "raw html", "unstyled"],
    action: "disable-css",
    icon: "🎨",
    label: "Toggle CSS",
    description: "Strip all page styles",
  },
  {
    keyword: "outline elements",
    aliases: ["show layout", "debug layout", "boxes"],
    action: "outline-elements",
    icon: "📐",
    label: "Toggle Layout Outlines",
    description: "Show borders around all elements",
  },
];
